### PR TITLE
Fix import facades

### LINKED ISSUE #251: `File` class in current namespace mistaken for Facade alias
image

### PR DESCRIPTION
**Pull request by driftingly**
This PR aims to fix #251 and #252.

- Removes `Linters\ImportFacades::class` from both Tighten and Laravel presets
- Adds new `Tighten\TLint\Linters\FullyQualifiedFacades` linter
- Adds new `Tighten\TLint\Formatters\FullyQualifiedFacades` formatter

The `FullyQualifiedFacades` forces `use Illuminate/Support/Facades/Cache;` over `use Cache;`

**This only affects `use` statements.**

## Linter

- Triggers on facade alias use (`use Cache;`)
- Does not trigger when an "alias" is used without an import statement
  - This avoids false positives where you have a file in the same directory named the same as a facade
- Does not trigger when the facade is correctly imported (`use Illuminate/Support/Facades/Cache;`)

```php
<?php

use Illuminate\Support\Facades\Cache;

$abc = Cache::get('abc');
```

```php
<?php

namespace App\Utilities;

use Illuminate\Support\Facades\Cache;

class SuperCacher
{
    public function doThing()
    {
        return Cache::get('abc');
    }
}
```

## Formatter

- Updates aliases to fully qualified facades
  - `use DB;` => `use Illuminate\Support\Facades\DB;`

### CODE REVIEW

File: tests/Formatting/Formatters/FullyQualifiedFacadesTest.php [hunk 1]
```diff
@@ -0,0 +1,168 @@
...
+use Illuminate\Support\Facades\Storage;
+
+return true;
+file;
+
+        $this->assertSame($expected, $formatted);
+    }
+
+    /** @test */
+    public function fixes_facade_aliases_when_file_not_namespaced()
```
Comment (driftingly) [inline tests/Formatting/Formatters/FullyQualifiedFacadesTest.php:42]: Should we only fix on namespaced files?

Comment (mattstauffer) [reply tests/Formatting/Formatters/FullyQualifiedFacadesTest.php:42]: I *think* I'm ok with us using the alias in non-namespaced files, but I don't really have a super strong opinion?

File: src/Formatters/FullyQualifiedFacades.php [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+        $oldStmts = $parser->parse($this->code);
+        $oldTokens = $lexer->getTokens();
+
+        $newStmts = $traverser->traverse($oldStmts);
+
+        if ($newStmts[0] instanceof Namespace_) {
+            $newStmts[0]->stmts = $this->transformFacadesToFullyQualified($newStmts[0]->stmts);
+        } elseif (count($newStmts) && ($newStmts[0] instanceof Use_ || $newStmts[0] instanceof UseUse)) {
+            $newStmts = $this->transformFacadesToFullyQualified($newStmts);
+        }
```
Comment (mattstauffer) [inline src/Formatters/FullyQualifiedFacades.php:38]: Is there another situation other than these two? Where `count($newStmts)` returns empty or its first entry isn't an instance of `use`? If so, do we need to catch it or else we will be not transforming? If not, should this just be an `else`?

File: tests/Formatting/Formatters/FullyQualifiedFacadesTest.php (hunk 1 above)
Comment (mattstauffer) [reply tests/Formatting/Formatters/FullyQualifiedFacadesTest.php:42]: Just asked everyone in Tighten to vote, so we'll know soon.

File: tests/Formatting/Formatters/FullyQualifiedFacadesTest.php [hunk 3]
```diff
@@ -0,0 +1,168 @@
...
+use Illuminate\Support\Facades\Storage;
+
+return true;
+file;
+
+        $this->assertSame($expected, $formatted);
+    }
+
+    /** @test */
+    public function fixes_facade_aliases_mixed_with_valid_use_statements()
```
Comment (mattstauffer) [inline tests/Formatting/Formatters/FullyQualifiedFacadesTest.php:68]: Could you also run a test where it's not the first entry?

File: tests/Formatting/Formatters/FullyQualifiedFacadesTest.php [hunk 4]
```diff
@@ -0,0 +1,168 @@
...
+
+use Shortcut;
+
+return true;
+file;
+
+        $formatted = (new TFormat)->format(new FullyQualifiedFacades($file));
+
+        $this->assertSame($file, $formatted);
+    }
```
Comment (mattstauffer) [inline tests/Formatting/Formatters/FullyQualifiedFacadesTest.php:167]: Can you add another test with the problem we were testing?

```php
<?php

namespace App\Utilities;

class Stuff
{
    public function doStuff()
    {
        return File::otherStuff();
    }
}
```

But `File` here is referencing `App\Utilities\File`, not `Illuminate\Support\Facades\File`.

I don't even know how we'll address this, TBH... hopefully it's possible?

File: tests/Linting/Linters/FullyQualifiedFacadesTest.php [hunk 5]
```diff
@@ -0,0 +1,152 @@
...
+
+        $lints = (new TLint)->lint(
+            new FullyQualifiedFacades($file)
+        );
+
+        $this->assertEmpty($lints);
+    }
+
+    /** @test */
+    public function does_not_trigger_on_alias_usage_without_import()
```
Comment (mattstauffer) [inline tests/Linting/Linters/FullyQualifiedFacadesTest.php:28]: oh wait.. so you're making the lint NOT trigger here, but you ARE having the formatter fix it? if the linter isn't linting it we shouldn't format it.

File: tests/Linting/Linters/FullyQualifiedFacadesTest.php [hunk 6]
```diff
@@ -0,0 +1,152 @@
...
+    }
+}
+file;
+
+        $lints = (new TLint)->lint(
+            new FullyQualifiedFacades($file)
+        );
+
+        $this->assertEmpty($lints);
+    }
```
Comment (mattstauffer) [inline tests/Linting/Linters/FullyQualifiedFacadesTest.php:151]: Can we also add the same test I requested above, where there's a class in the same namespace as my current test that has the same name as one of the Facade aliases?

**Review by mattstauffer — CHANGES_REQUESTED** [review]
Great work! Some notes

File: tests/Formatting/Formatters/FullyQualifiedFacadesTest.php (hunk 1 above)
Comment (driftingly) [reply tests/Formatting/Formatters/FullyQualifiedFacadesTest.php:42]: Looks like the vote was for consistency:

```php
<?php

use Illuminate\Support\Facades\Cache;

$abc = Cache::get('abc');
```

```php
<?php

namespace App\Utilities;

use Illuminate\Support\Facades\Cache;

class SuperCacher
{
    public function doThing()
    {
        return Cache::get('abc');
    }
}
```

File: tests/Formatting/Formatters/FullyQualifiedFacadesTest.php (hunk 3 above)
Comment (driftingly) [reply tests/Formatting/Formatters/FullyQualifiedFacadesTest.php:68]: This test also has `use Storage;` => `use Illuminate\Support\Facades\Storage;`

File: tests/Formatting/Formatters/FullyQualifiedFacadesTest.php (hunk 4 above)
Comment (driftingly) [reply tests/Formatting/Formatters/FullyQualifiedFacadesTest.php:190]: Added. Right now we are only looking at and fixing import statements.

This is fine:
```php
<?php

namespace App\Utilities;

class Stuff
{
    public function doStuff()
    {
        return File::otherStuff();
    }
}
``` 

This will trigger an error with the linter and a fix with formatter
```php
<?php

namespace App\Utilities;

use File;

class Stuff
{
    public function doStuff()
    {
        return File::otherStuff();
    }
}
```

File: tests/Linting/Linters/FullyQualifiedFacadesTest.php (hunk 5 above)
Comment (driftingly) [reply tests/Linting/Linters/FullyQualifiedFacadesTest.php:72]: We only format the import statement.  So in the example below if File was imported as `use File;` it would have been formatted as `use Illuminate\Support\Facades\File;`.

Since I have added `does_not_trigger_on_alias_usage_without_import` to both linter and formatter test I've removed this one.

File: tests/Formatting/Formatters/FullyQualifiedFacadesTest.php (hunk 1 above)
Comment (mattstauffer) [reply tests/Formatting/Formatters/FullyQualifiedFacadesTest.php:42]: Yep, seems so! Honestly that's not my preference but I'm gonna go with the team :)

**Comment by mattstauffer** [comment]
Thanks for your updates @driftingly! Is this ready for review again?

**Comment by driftingly** [comment]
@mattstauffer Not quite.  I'll ping you when I have it dialled in.

File: src/Linters/FullyQualifiedFacades.php [hunk 7]
```diff
@@ -0,0 +1,57 @@
...
+        $visitor = new FindingVisitor(function (Node $node) {
+            static $hasNamespace = false;
+
+            if ($node instanceof Node\Stmt\Namespace_) {
+                $hasNamespace = true;
+            }
+
+            static $useNames = [];
+            static $useAliases = [];
+
```
[the remark this answers is not in the document]
Comment (driftingly) [reply src/Linters/FullyQualifiedFacades.php]: Nope, just a copy/paste issue.  I've refactored this linter quite a bit since.

File: src/Linters/FullyQualifiedFacades.php [hunk 8]
```diff
@@ -0,0 +1,57 @@
...
+            if ($node instanceof Node\Stmt\GroupUse) {
```
[the remark this answers is not in the document]
Comment (driftingly) [reply src/Linters/FullyQualifiedFacades.php:29]: Not applicable with refactor.

File: src/Linters/FullyQualifiedFacades.php [hunk 9]
```diff
@@ -0,0 +1,57 @@
...
+                foreach ($node->uses as $use) {
+                    $useNames[] = Name::concat($node->prefix, $use->name)->toString();
+                    $useAliases[] = $use->getAlias();
+                }
+            } elseif ($node instanceof Node\Stmt\UseUse) {
+                $useNames[] = $node->name->toString();
+                $useAliases[] = $node->getAlias();
+            }
+
+            return $node instanceof Node\Expr\StaticCall
```
[the remark this answers is not in the document]
Comment (driftingly) [reply src/Linters/FullyQualifiedFacades.php]: Not applicable with refactor.

File: tests/Linting/Linters/FullyQualifiedFacadesTest.php (hunk 6 above)
Comment (driftingly) [reply tests/Linting/Linters/FullyQualifiedFacadesTest.php:200]: Done.

**Comment by driftingly** [comment]
@bakerkretzmar This linter/formatter doesn't look through the codebase for aliases used to add imports statements, it just updates the existing import statements from aliases to FQCN.

If you'd rather these do that I can work towards that goal. 
We would have false positives - eg `ignores_files_in_same_directory_with_same_name_as_facade_alias` test.
The file includes a file in the same directory with the same name as a facade alias.  

```php
<?php

namespace App\Utilities;

class Stuff
{
    public function doStuff()
    {
        return File::otherStuff();
    }
}
```

**Comment by bakerkretzmar** [comment]
@driftingly yeah sorry, my comment wasn't very clear lol. My `ImportFacades` formatter is poorly named, but the code was supposed to do exactly what your `FullyQualifiedFacades` formatter does—replace alias imports like `use Cache;` with fully namespaced imports. So we can just delete my `ImportFacades` formatter. I'm happy to do this and move the tests if you want, and then I think this is ready to merge.

Your linter is also great. I think we should add both your linter and formatter to the Tighten preset (at least), but I think that needs a major release.

---

The adjacent file thing is still an issue, but not for this PR because you've improved it already and it's going to need a different approach I think.

Before this PR, as you mentioned, we were getting false positives, so this:

```php
<?php

namespace App;

Date::now();
```

would lint even if there **is** a `Date` class beside that file.

But TLint doesn't actually look at whether that file exists, ever—so after this PR, we'll instead have false negatives: the example above will **not** lint, even if there **isn't** a `Date` class beside it. This new false negative behaviour is better in my opinion, but we could still be fix/improve it down the road.

**Review by bakerkretzmar — APPROVED** [review]
Awesome work here @driftingly!!
